name: Deployment

on:
  push:
    branches:
      - main
      - portfolio-v1

jobs:
  run-inline-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installing and Configuring AWS CLI
        run: |
          echo "Running deployment script..."
          sudo apt-get update
          sudo apt-get install -y unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version 
          echo "configuring aws credentials"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Application Build Step
        run: |
          echo "Installing npm dependencies"
          npm install --force
          echo "Building app using npm run build"
          npm run build
          
      - name: Deploying app build files to S3
        run: |
          echo "Copying build folder to S3"
          aws s3 sync build/ {{ secrets.S3_URI }}
          
      - name: Invalidating Cloudfront cache
        run: |
          echo "Invalidating Cloudfront cache for /* path"
          aws cloudfront create-invalidation --distribution-id {{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Cleanup task
        run: |
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
